// data.js — Seed Data for EarnRadar
// In production, this is replaced by live API data from Cloudflare Workers

const CATEGORIES = [
  { id: "freelance", name: "عمل حر", icon: "🎨", color: "#00D4AA" },
  { id: "ai",        name: "ذكاء اصطناعي", icon: "🤖", color: "#7C3AED" },
  { id: "surveys",   name: "استبيانات", icon: "📋", color: "#3B82F6" },
  { id: "affiliate", name: "تسويق بالعمولة", icon: "🔗", color: "#F59E0B" },
  { id: "referral",  name: "إحالات", icon: "👥", color: "#EC4899" },
  { id: "cashback",  name: "كاش باك", icon: "💰", color: "#10B981" },
  { id: "apps",      name: "تطبيقات", icon: "📱", color: "#6366F1" },
  { id: "contests",  name: "مسابقات", icon: "🏆", color: "#EF4444" },
  { id: "remote",    name: "عمل عن بعد", icon: "💻", color: "#0EA5E9" },
  { id: "crypto",    name: "عملات رقمية", icon: "₿", color: "#F97316" },
  { id: "grants",    name: "منح", icon: "🎓", color: "#84CC16" },
  { id: "testing",   name: "اختبارات", icon: "🧪", color: "#A78BFA" },
  { id: "trading",   name: "تداول", icon: "📈", color: "#06B6D4" },
  { id: "other",     name: "أخرى", icon: "📦", color: "#8B9CC8" }
];

const SOURCES = [
  { id: "reddit", name: "Reddit API", status: "active", count: 134 },
  { id: "hackernews", name: "Hacker News", status: "active", count: 89 },
  { id: "producthunt", name: "Product Hunt", status: "active", count: 76 },
  { id: "github", name: "GitHub Trending", status: "active", count: 45 },
  { id: "remoteok", name: "RemoteOK", status: "active", count: 203 },
  { id: "swagbucks", name: "Survey Sites RSS", status: "active", count: 38 },
  { id: "aitoolsdirectory", name: "AI Tools RSS", status: "active", count: 67 },
  { id: "freeelancer", name: "Freelancer RSS", status: "error", count: 0 },
  { id: "upwork", name: "Upwork Feed", status: "active", count: 158 },
  { id: "fiverr", name: "Fiverr Insights", status: "active", count: 91 },
  { id: "techcrunch", name: "TechCrunch RSS", status: "active", count: 29 },
  { id: "indiehackers", name: "Indie Hackers", status: "active", count: 53 }
];

const OPPORTUNITIES = [
  {
    id: 1,
    title: "Upwork — منصة العمل الحر الأكبر عالمياً",
    description: "اكسب من مهاراتك في التصميم والبرمجة والكتابة والتسويق عبر أكبر منصة عمل حر في العالم بأكثر من 5 مليون وظيفة.",
    fullDescription: "Upwork هي المنصة الرائدة في مجال العمل الحر حول العالم، تتيح لك إنشاء ملف شخصي احترافي والتقدم لآلاف المشاريع يومياً. تشمل المجالات: البرمجة، التصميم، الكتابة، التسويق، المحاسبة، والمزيد. يمكنك البدء مجاناً وكسب من $5 إلى $200+ في الساعة حسب خبرتك.",
    category: "freelance",
    status: "recommended",
    emoji: "💼",
    earnings: "$500 - $5000/شهر",
    earningLevel: "high",
    trustScore: 9.5,
    rating: 4.7,
    reviews: 12840,
    country: "عالمي",
    devices: "both",
    payment: ["paypal", "bank", "payoneer"],
    minWithdraw: "$100",
    isFree: true,
    difficulty: "متوسط",
    timeRequired: "دوام كامل أو جزئي",
    url: "https://upwork.com",
    tags: ["عمل حر", "برمجة", "تصميم", "كتابة", "تسويق"],
    source: "upwork",
    publishedAt: new Date(Date.now() - 1 * 3600000).toISOString(),
    views: 28450
  },
  {
    id: 2,
    title: "Claude AI — اكسب من مساعدة في التدريب",
    description: "برنامج Anthropic لمكافأة المساهمين في تحسين نماذج الذكاء الاصطناعي عبر تقييم وإنشاء محادثات عالية الجودة.",
    fullDescription: "يمكنك الكسب من خلال المساهمة في تدريب نماذج الذكاء الاصطناعي. تقوم بتقييم ردود النماذج، كتابة محادثات نموذجية، أو اختبار القدرات. الدفع يتم عبر Scale AI وشركاء آخرين. فرصة رائعة للراغبين في العمل مع تقنيات الذكاء الاصطناعي.",
    category: "ai",
    status: "trending",
    emoji: "🤖",
    earnings: "$15 - $50/ساعة",
    earningLevel: "medium",
    trustScore: 9.8,
    rating: 4.9,
    reviews: 3210,
    country: "عالمي",
    devices: "desktop",
    payment: ["paypal", "bank"],
    minWithdraw: "$50",
    isFree: true,
    difficulty: "متوسط",
    timeRequired: "مرن",
    url: "https://scale.ai",
    tags: ["ذكاء اصطناعي", "تقييم بيانات", "RLHF", "تدريب نماذج"],
    source: "reddit",
    publishedAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    views: 15200
  },
  {
    id: 3,
    title: "Swagbucks — استبيانات وإعلانات مدفوعة",
    description: "منصة مكافآت تدفع مقابل ملء الاستبيانات، مشاهدة الإعلانات، التسوق، وألعاب أونلاين. متاح عالمياً.",
    fullDescription: "Swagbucks هي إحدى أقدم وأكثر منصات المكافآت موثوقية. تكسب نقاط (SB) مقابل: الاستبيانات (50-400 SB)، مشاهدة مقاطع فيديو، التسوق الإلكتروني (1-10% كاش باك)، تثبيت التطبيقات، والألعاب. 100 SB = $1. يمكن السحب عبر PayPal أو بطاقات هدايا.",
    category: "surveys",
    status: "new",
    emoji: "📋",
    earnings: "$50 - $300/شهر",
    earningLevel: "low",
    trustScore: 8.5,
    rating: 4.2,
    reviews: 45600,
    country: "عالمي",
    devices: "both",
    payment: ["paypal", "gift"],
    minWithdraw: "$3",
    isFree: true,
    difficulty: "سهل",
    timeRequired: "ساعة يومياً",
    url: "https://swagbucks.com",
    tags: ["استبيانات", "مكافآت", "كاش باك", "إعلانات"],
    source: "swagbucks",
    publishedAt: new Date(Date.now() - 30 * 60000).toISOString(),
    views: 9870
  },
  {
    id: 4,
    title: "Amazon Associates — التسويق بالعمولة",
    description: "برنامج العمولة الأشهر عالمياً. اكسب 1-10% عمولة من كل مبيعة تتم عبر روابطك التابعة لأمازون.",
    fullDescription: "Amazon Associates هو برنامج الإحالة الأكثر شعبية عالمياً. يمكنك الترويج لملايين المنتجات وكسب عمولة تتراوح بين 1% و10% حسب الفئة. كل ما تحتاجه موقع إلكتروني، قناة يوتيوب، أو صفحة سوشيال ميديا ذات متابعين.",
    category: "affiliate",
    status: "recommended",
    emoji: "🔗",
    earnings: "$100 - $10000/شهر",
    earningLevel: "variable",
    trustScore: 9.7,
    rating: 4.5,
    reviews: 89200,
    country: "عالمي",
    devices: "both",
    payment: ["bank", "gift", "check"],
    minWithdraw: "$10",
    isFree: true,
    difficulty: "متوسط",
    timeRequired: "يتطلب جمهور مسبق",
    url: "https://affiliate-program.amazon.com",
    tags: ["عمولة", "أمازون", "تسويق", "روابط"],
    source: "reddit",
    publishedAt: new Date(Date.now() - 4 * 3600000).toISOString(),
    views: 22100
  },
  {
    id: 5,
    title: "Referral Hero — تتبع برامج الإحالة بذكاء",
    description: "دليل شامل لأفضل برامج الإحالة المدفوعة في 2025. شركات تدفع حتى $500 لكل صديق تجلبه.",
    fullDescription: "برامج الإحالة من أسهل طرق الكسب بدون مهارات خاصة. أبرز البرامج: Robinhood ($5-20)، Coinbase ($10)، Rakuten ($30)، Swagbucks ($3)، Honey ($5)، واللائحة تطول. كل ما تفعله هو مشاركة رابط خاص بك مع الأصدقاء والعائلة.",
    category: "referral",
    status: "new",
    emoji: "👥",
    earnings: "$10 - $500/إحالة",
    earningLevel: "medium",
    trustScore: 8.0,
    rating: 4.3,
    reviews: 5430,
    country: "عالمي",
    devices: "both",
    payment: ["paypal", "bank", "crypto"],
    minWithdraw: "متفاوت",
    isFree: true,
    difficulty: "سهل جداً",
    timeRequired: "دقائق",
    url: "https://referralhero.com",
    tags: ["إحالات", "مكافآت", "أصدقاء", "سهل"],
    source: "reddit",
    publishedAt: new Date(Date.now() - 45 * 60000).toISOString(),
    views: 6700
  },
  {
    id: 6,
    title: "Rakuten — كاش باك على كل مشترياتك",
    description: "احصل على استرداد نقدي فعلي عند التسوق من 3500+ متجر عبر الإنترنت. الكاش باك يصل حتى 40%.",
    fullDescription: "Rakuten (سابقاً Ebates) يمنحك كاش باك حقيقي عند تسوقك من ماركات عالمية كـ Nike, ASOS, Booking.com, eBay وغيرها. كل ما عليك هو تثبيت الإضافة أو استخدام الموقع قبل الشراء. تصل إليك شيكات الكاش باك ربع سنوياً.",
    category: "cashback",
    status: "recommended",
    emoji: "💰",
    earnings: "1-40% على كل عملية شراء",
    earningLevel: "variable",
    trustScore: 9.2,
    rating: 4.6,
    reviews: 67800,
    country: "الولايات المتحدة، كندا، أوروبا",
    devices: "both",
    payment: ["paypal", "check"],
    minWithdraw: "$5.01",
    isFree: true,
    difficulty: "سهل جداً",
    timeRequired: "لا وقت إضافي",
    url: "https://rakuten.com",
    tags: ["كاش باك", "تسوق", "استرداد", "إضافة متصفح"],
    source: "reddit",
    publishedAt: new Date(Date.now() - 6 * 3600000).toISOString(),
    views: 18900
  },
  {
    id: 7,
    title: "UserTesting — اختبر التطبيقات وأنت في المنزل",
    description: "احصل على $10 مقابل كل 20 دقيقة تقضيها في اختبار مواقع وتطبيقات وتسجيل تعليقاتك الصوتية.",
    fullDescription: "UserTesting تدفع للمستخدمين العاديين مقابل اختبار مواقع وتطبيقات وإعطاء آرائهم. كل مهمة تستغرق 10-20 دقيقة وتدفع $4-$60. كل ما تحتاجه: ميكروفون، اتصال إنترنت، وإجادة القراءة بالإنجليزية. الدفع عبر PayPal خلال 7 أيام.",
    category: "testing",
    status: "trending",
    emoji: "🧪",
    earnings: "$10 - $60/مهمة",
    earningLevel: "medium",
    trustScore: 8.8,
    rating: 4.4,
    reviews: 23100,
    country: "عالمي (معظم الدول)",
    devices: "both",
    payment: ["paypal"],
    minWithdraw: "$10",
    isFree: true,
    difficulty: "سهل",
    timeRequired: "20 دق/مهمة",
    url: "https://usertesting.com",
    tags: ["اختبار", "UX", "تعليقات", "PayPal"],
    source: "reddit",
    publishedAt: new Date(Date.now() - 3 * 3600000).toISOString(),
    views: 14500
  },
  {
    id: 8,
    title: "Replit Bounties — فرص برمجة مدفوعة",
    description: "اكسب مقابل حل تحديات برمجية يطرحها مستخدمو Replit. المكافآت تتراوح من $50 إلى $5000.",
    fullDescription: "Replit Bounties منصة تربط المبرمجين بأصحاب العمل الراغبين في حل مشاكل تقنية. يمكنك تصفح المهام المتاحة، التقدم إليها، وتنفيذها مباشرة في متصفحك. فرصة ممتازة للمبرمجين المبتدئين والمتقدمين لكسب دخل إضافي.",
    category: "freelance",
    status: "new",
    emoji: "💻",
    earnings: "$50 - $5000/مهمة",
    earningLevel: "high",
    trustScore: 8.6,
    rating: 4.3,
    reviews: 4200,
    country: "عالمي",
    devices: "desktop",
    payment: ["paypal", "bank"],
    minWithdraw: "$10",
    isFree: true,
    difficulty: "متقدم",
    timeRequired: "حسب المشروع",
    url: "https://replit.com/bounties",
    tags: ["برمجة", "باونتي", "مشاريع", "تقني"],
    source: "hackernews",
    publishedAt: new Date(Date.now() - 20 * 60000).toISOString(),
    views: 8900
  },
  {
    id: 9,
    title: "Fiverr — بيع خدماتك من $5 إلى $10,000",
    description: "أنشئ خدماتك الاحترافية وبيعها لملايين المشترين حول العالم في أي مجال تتقنه.",
    fullDescription: "Fiverr تتيح لك عرض خدماتك بدءاً من $5. المجالات الأعلى طلباً: تصميم اللوجو، كتابة المحتوى، SEO، إدارة السوشيال ميديا، التعليق الصوتي، الترجمة، والبرمجة. يكسب أفضل البائعين $10,000+ شهرياً. تأخذ Fiverr 20% عمولة.",
    category: "freelance",
    status: "recommended",
    emoji: "🌟",
    earnings: "$100 - $10000/شهر",
    earningLevel: "high",
    trustScore: 9.0,
    rating: 4.5,
    reviews: 156000,
    country: "عالمي",
    devices: "both",
    payment: ["paypal", "bank", "payoneer"],
    minWithdraw: "$20",
    isFree: true,
    difficulty: "متوسط",
    timeRequired: "مرن",
    url: "https://fiverr.com",
    tags: ["عمل حر", "خدمات", "تصميم", "كتابة", "برمجة"],
    source: "reddit",
    publishedAt: new Date(Date.now() - 8 * 3600000).toISOString(),
    views: 34200
  },
  {
    id: 10,
    title: "Binance Earn — أربح من عملاتك الرقمية",
    description: "اكسب فائدة سنوية حتى 20% على عملاتك الرقمية عبر منتجات Binance Earn المتنوعة.",
    fullDescription: "Binance Earn يتيح لك تحقيق دخل سلبي من عملاتك الرقمية دون الحاجة للتداول. خيارات التوفير: Flexible Savings (سحب فوري)، Locked Staking (عوائد أعلى)، Dual Investment، وLaunchpool. معدلات العائد تتراوح 3%-20% سنوياً حسب العملة والمدة.",
    category: "crypto",
    status: "trending",
    emoji: "₿",
    earnings: "3-20% سنوياً",
    earningLevel: "medium",
    trustScore: 8.3,
    rating: 4.1,
    reviews: 89500,
    country: "عالمي (مع بعض القيود)",
    devices: "both",
    payment: ["crypto"],
    minWithdraw: "يعتمد على العملة",
    isFree: true,
    difficulty: "متوسط",
    timeRequired: "استثمار طويل الأمد",
    url: "https://binance.com/earn",
    tags: ["كريبتو", "ستاكينج", "دخل سلبي", "فائدة"],
    source: "reddit",
    publishedAt: new Date(Date.now() - 5 * 3600000).toISOString(),
    views: 19600
  },
  {
    id: 11,
    title: "YCombinator Grants — منحة $500K للمشاريع الناشئة",
    description: "برنامج YC يوفر $500,000 لكل شركة ناشئة مقبولة مع إرشاد من أبرز المستثمرين في وادي السيليكون.",
    fullDescription: "Y Combinator هو أبرز مسرع أعمال في العالم. تحصل شركتك الناشئة على $500,000 وثلاثة أشهر من الإرشاد المكثف، ثم تعرض مشروعك أمام مئات المستثمرين في Demo Day. الخريجون يشملون Airbnb, Stripe, Coinbase, Dropbox. التقديم مفتوح مرتين سنوياً.",
    category: "grants",
    status: "new",
    emoji: "🎓",
    earnings: "$500,000 منحة",
    earningLevel: "high",
    trustScore: 9.9,
    rating: 4.9,
    reviews: 1230,
    country: "عالمي",
    devices: "desktop",
    payment: ["bank"],
    minWithdraw: "لا ينطبق",
    isFree: true,
    difficulty: "صعب جداً",
    timeRequired: "التزام كامل",
    url: "https://ycombinator.com/apply",
    tags: ["منحة", "ناشئة", "استثمار", "YC", "وادي السيليكون"],
    source: "hackernews",
    publishedAt: new Date(Date.now() - 12 * 3600000).toISOString(),
    views: 45800
  },
  {
    id: 12,
    title: "99designs — مسابقات التصميم الجرافيكي",
    description: "شارك في مسابقات التصميم وفُز بمبالغ من $99 إلى $1,299 لكل مشروع فائز.",
    fullDescription: "99designs تتيح للمصممين المشاركة في مسابقات حيث يطرح أصحاب العمل مشروعاً (لوجو، موقع، إلخ) ويقدم المصممون أعمالهم. الفائز يحصل على المبلغ كاملاً. الميزة: تبني ملفاً متنوعاً وتتعلم من المنافسة. مناسب للمصممين المبتدئين.",
    category: "contests",
    status: "new",
    emoji: "🏆",
    earnings: "$99 - $1299/فوز",
    earningLevel: "variable",
    trustScore: 8.4,
    rating: 4.2,
    reviews: 18900,
    country: "عالمي",
    devices: "desktop",
    payment: ["paypal", "bank"],
    minWithdraw: "$20",
    isFree: true,
    difficulty: "يتطلب مهارة تصميم",
    timeRequired: "حسب المشروع",
    url: "https://99designs.com",
    tags: ["تصميم", "مسابقات", "جرافيك", "لوجو"],
    source: "reddit",
    publishedAt: new Date(Date.now() - 15 * 60000).toISOString(),
    views: 7600
  }
];

// i18n strings
const TRANSLATIONS = {
  ar: {
    newToday: "جديد اليوم",
    trending: "الفرص الرائجة",
    allOpps: "جميع الفرص",
    topRated: "الأعلى تقييماً",
    categories: "التصنيفات",
    sources: "المصادر النشطة",
    visitSite: "زيارة الموقع",
    save: "حفظ",
    earnings: "الأرباح المتوقعة",
    trust: "موثوقية",
    rating: "التقييم",
    countries: "الدول",
    devices: "الأجهزة",
    payment: "طريقة الدفع",
    minWithdraw: "الحد الأدنى للسحب",
    difficulty: "مستوى الصعوبة",
    time: "الوقت المطلوب",
    free: "مجاني",
    statusNew: "جديد",
    statusTrending: "رائج",
    statusRecommended: "موصى به",
    searchPlaceholder: "ابحث عن فرصة...",
    loadMore: "تحميل المزيد",
    refresh: "تحديث",
    results: "فرصة",
    noResults: "لا توجد نتائج"
  },
  en: {
    newToday: "New Today",
    trending: "Trending Opportunities",
    allOpps: "All Opportunities",
    topRated: "Top Rated",
    categories: "Categories",
    sources: "Active Sources",
    visitSite: "Visit Site",
    save: "Save",
    earnings: "Expected Earnings",
    trust: "Trust Score",
    rating: "Rating",
    countries: "Countries",
    devices: "Devices",
    payment: "Payment Method",
    minWithdraw: "Min Withdrawal",
    difficulty: "Difficulty",
    time: "Time Required",
    free: "Free",
    statusNew: "New",
    statusTrending: "Trending",
    statusRecommended: "Recommended",
    searchPlaceholder: "Search opportunities...",
    loadMore: "Load More",
    refresh: "Refresh",
    results: "opportunities",
    noResults: "No results found"
  }
};
